<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


return [
    'results' => [
        '100' => 'SUCCESS',
        '101' => 'FAILURE',
        '102' => 'RECORD_INSERTED',
        '103' => 'RECORD_ALREADY_EXIST',
        '104' => 'BLOCKED_USER',
        '105' => 'NO_RECORDS',
        '106' => 'RECORD_UPDATED',
        '107' => 'INVALID_SKILL_ID',
        '108' => 'ALREADY_SELECTED',
        '109' => 'INVALID_USER_ID',
        '110' => 'NUMERIC_VALUE_REQUIRED',
        '111' => 'ALREADY_VERIFIED',
        '112' => 'VERIFIED',
        '113' => 'INVALID_VERIFICATION_CODE',
        '114' => 'NO_SKILLS_AVAILABLE',
        '115' => 'INSUFFICIENT_BALANCE',
        '116' => 'ANOTHER_DEVICE_EXIST',
        '117' => 'SMS_SENDING_FAILURE',
        '118' => 'EMAIL_UPDATED',
        '119' => 'PHONE_UPDATED',
        '120' => 'BOTH_UPDATED',
        '121' => 'NOTHING_UPDATED',
        '122' => 'EMAIL_ALREADY_EXIST',
        '123' => 'ALREADY_UPDATED',
        '124' => 'SMS_RESEND',
        '125' => 'INVALID_SENDER_ID',
        '126' => 'INVALID_RECEIVER_ID',
        '127' => 'INVITATION_SEND',
        '128' => 'INVITATION_ALREADY_SEND',
        '129' => 'INVALID_ACCOUNT_ID',
        '130' => 'OTHER_DEVICE',
        '131' => 'VALIDATION_PENDING',
        '132' => 'INVALID_FOLLOWER_ID',
        '133' => 'INVALID_FOLLOWING_ID',
        '134' => 'ALREADY_FOLLOWING',
        '135' => 'ALREADY_UNFOLLOW',
        '136' => 'MUST_BE_FAVO_USER',
        '137' => 'INVALID_PROVIDER_ID',
        '138' => 'ALREADY_FAVOURITE',
        '139' => 'NOT_VALID_FOR_API',
        '140' => 'ATTEMPT_EXCEED',
        '141' => 'INVALID_ATTEMPT',
        '142' => 'QUESTION_ALREADY_ANSWER',
        '143' => 'IDOLOGY_VERIFICATION_FAIL',
        '144' => 'TOO_FEW_ANSWERS_SUBMITTED_FOR_IQ_TYPE',
        '145' => 'GROUP_CREATED',
        '146' => 'GROUP_ALREADY_EXIST',
        '147' => 'INVALID_GROUP_ID',
        '148' => 'GROUP_DEFINED_SUCCESSFULLY',
        '149' => 'INVALID_GROUP_TYPE',
        '150' => 'SERVICE_REGION_NOT_DEFINED_FOR_USER',
        '151' => 'GROUP_EXIST_SAME_NAME',
        '152' => 'NO_GROUP_MEMBERS',
        '153' => 'IMAGE_UPDATED',
        '154' => 'INVALID_LICENSE_ID',
        '155' => 'LICENSE_ALREADY_REMOVED',
        '156' => 'INVALID_INSURANCE_ID',
        '157' => 'INSURANCE_ALREADY_REMOVED',
        '158' => 'INVALID_WORK_ID',
        '159' => 'WORK_ALREADY_REMOVED',
        '160' => 'INVALID_MEMBER_ID',
        '210' => 'NOT_FOUND invalid call',
        '211' => 'INVALID_USER_PUBLIC_KEY',
        '212' => 'INVALID_APP_VERSION_KEY',
        '300' => 'FILE_UPLOAD_ERROR',
        '400' => 'INVALID_PARAMETERS',
        '401' => 'NO_DATA',
        '402' => 'NO_SERVICE_DATA',
        '404' => 'URL_NOT_FOUND',
        '405' => 'METHOD_NOT_ALLOWED',
        '500' => 'INTERNAL_SERVER_ERROR',
        'root' => 'https://www.callme4.com:8443/uploaded_file',
    ]
];

?>
